# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_settings.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName(_fromUtf8("Settings"))
        Settings.resize(620, 442)
        self.gridLayout = QtGui.QGridLayout(Settings)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(Settings)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName(_fromUtf8("generalTab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.generalTab)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 2, 0, 1, 1)
        self.selectGroup = QtGui.QGroupBox(self.generalTab)
        self.selectGroup.setObjectName(_fromUtf8("selectGroup"))
        self.gridLayout_3 = QtGui.QGridLayout(self.selectGroup)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.rubberWidth = QtGui.QDoubleSpinBox(self.selectGroup)
        self.rubberWidth.setToolTip(_fromUtf8(""))
        self.rubberWidth.setDecimals(1)
        self.rubberWidth.setSingleStep(1.0)
        self.rubberWidth.setProperty("value", 2.0)
        self.rubberWidth.setObjectName(_fromUtf8("rubberWidth"))
        self.gridLayout_3.addWidget(self.rubberWidth, 2, 1, 1, 1)
        self.selectTolerance = QtGui.QDoubleSpinBox(self.selectGroup)
        self.selectTolerance.setSingleStep(0.1)
        self.selectTolerance.setProperty("value", 0.3)
        self.selectTolerance.setObjectName(_fromUtf8("selectTolerance"))
        self.gridLayout_3.addWidget(self.selectTolerance, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.selectGroup)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.rubberColor = QtGui.QLabel(self.selectGroup)
        self.rubberColor.setText(_fromUtf8(""))
        self.rubberColor.setObjectName(_fromUtf8("rubberColor"))
        self.gridLayout_3.addWidget(self.rubberColor, 2, 2, 1, 1)
        self.units = QtGui.QWidget(self.selectGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.units.sizePolicy().hasHeightForWidth())
        self.units.setSizePolicy(sizePolicy)
        self.units.setObjectName(_fromUtf8("units"))
        self.gridLayout_2 = QtGui.QGridLayout(self.units)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pixels = QtGui.QRadioButton(self.units)
        self.pixels.setChecked(True)
        self.pixels.setObjectName(_fromUtf8("pixels"))
        self.selectUnits = QtGui.QButtonGroup(Settings)
        self.selectUnits.setObjectName(_fromUtf8("selectUnits"))
        self.selectUnits.addButton(self.pixels)
        self.gridLayout_2.addWidget(self.pixels, 2, 0, 1, 1)
        self.map = QtGui.QRadioButton(self.units)
        self.map.setChecked(False)
        self.map.setObjectName(_fromUtf8("map"))
        self.selectUnits.addButton(self.map)
        self.gridLayout_2.addWidget(self.map, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.units, 1, 2, 1, 1)
        self.rubberIcon = QtGui.QComboBox(self.selectGroup)
        self.rubberIcon.setObjectName(_fromUtf8("rubberIcon"))
        self.rubberIcon.addItem(_fromUtf8(""))
        self.rubberIcon.addItem(_fromUtf8(""))
        self.rubberIcon.addItem(_fromUtf8(""))
        self.rubberIcon.addItem(_fromUtf8(""))
        self.rubberIcon.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.rubberIcon, 3, 2, 1, 1)
        self.rubberSize = QtGui.QSpinBox(self.selectGroup)
        self.rubberSize.setMinimum(1)
        self.rubberSize.setMaximum(50)
        self.rubberSize.setObjectName(_fromUtf8("rubberSize"))
        self.gridLayout_3.addWidget(self.rubberSize, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.selectGroup)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 2, 1)
        self.gridLayout_10.addWidget(self.selectGroup, 0, 0, 1, 1)
        self.tabWidget.addTab(self.generalTab, _fromUtf8(""))
        self.observationTab = QtGui.QWidget()
        self.observationTab.setObjectName(_fromUtf8("observationTab"))
        self.formLayout_2 = QtGui.QFormLayout(self.observationTab)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.observationTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 2)
        self.obsDefaultPrecisionDistance = QtGui.QDoubleSpinBox(self.groupBox)
        self.obsDefaultPrecisionDistance.setDecimals(4)
        self.obsDefaultPrecisionDistance.setMaximum(100.0)
        self.obsDefaultPrecisionDistance.setSingleStep(0.005)
        self.obsDefaultPrecisionDistance.setProperty("value", 0.025)
        self.obsDefaultPrecisionDistance.setObjectName(_fromUtf8("obsDefaultPrecisionDistance"))
        self.gridLayout_7.addWidget(self.obsDefaultPrecisionDistance, 0, 2, 1, 1)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.observationTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 1)
        self.obsOrientationLength = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.obsOrientationLength.setDecimals(1)
        self.obsOrientationLength.setProperty("value", 8.0)
        self.obsOrientationLength.setObjectName(_fromUtf8("obsOrientationLength"))
        self.gridLayout_8.addWidget(self.obsOrientationLength, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_8.addWidget(self.label_8, 1, 0, 1, 1)
        self.obsOrientationDefaultPrecision = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.obsOrientationDefaultPrecision.setEnabled(True)
        self.obsOrientationDefaultPrecision.setMaximum(2.0)
        self.obsOrientationDefaultPrecision.setSingleStep(0.1)
        self.obsOrientationDefaultPrecision.setProperty("value", 0.5)
        self.obsOrientationDefaultPrecision.setObjectName(_fromUtf8("obsOrientationDefaultPrecision"))
        self.gridLayout_8.addWidget(self.obsOrientationDefaultPrecision, 0, 1, 1, 1)
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.groupBox_3)
        self.line_2 = QtGui.QFrame(self.observationTab)
        self.line_2.setMinimumSize(QtCore.QSize(30, 0))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.line_2)
        self.tabWidget.addTab(self.observationTab, _fromUtf8(""))
        self.intersectionTab = QtGui.QWidget()
        self.intersectionTab.setObjectName(_fromUtf8("intersectionTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.intersectionTab)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 5, 0, 1, 1)
        self.line = QtGui.QFrame(self.intersectionTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.intersectionTab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.advancedIntersectionWriteReport = QtGui.QCheckBox(self.groupBox_4)
        self.advancedIntersectionWriteReport.setObjectName(_fromUtf8("advancedIntersectionWriteReport"))
        self.gridLayout_11.addWidget(self.advancedIntersectionWriteReport, 4, 0, 1, 1)
        self.advancedIntersectionWritePoint = QtGui.QCheckBox(self.groupBox_4)
        self.advancedIntersectionWritePoint.setObjectName(_fromUtf8("advancedIntersectionWritePoint"))
        self.gridLayout_11.addWidget(self.advancedIntersectionWritePoint, 2, 0, 1, 1)
        self.intersecLSmaxIter = QtGui.QSpinBox(self.groupBox_4)
        self.intersecLSmaxIter.setProperty("value", 15)
        self.intersecLSmaxIter.setObjectName(_fromUtf8("intersecLSmaxIter"))
        self.gridLayout_11.addWidget(self.intersecLSmaxIter, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_11.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_11.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_11.addWidget(self.label_7, 1, 0, 1, 1)
        self.advancedIntersecLSconvergeThreshold = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.advancedIntersecLSconvergeThreshold.setDecimals(4)
        self.advancedIntersecLSconvergeThreshold.setMaximum(1.0)
        self.advancedIntersecLSconvergeThreshold.setSingleStep(0.01)
        self.advancedIntersecLSconvergeThreshold.setProperty("value", 0.0005)
        self.advancedIntersecLSconvergeThreshold.setObjectName(_fromUtf8("advancedIntersecLSconvergeThreshold"))
        self.gridLayout_11.addWidget(self.advancedIntersecLSconvergeThreshold, 0, 1, 1, 1)
        self.advancedIntersectionLayer = gui.QgsMapLayerComboBox(self.groupBox_4)
        self.advancedIntersectionLayer.setObjectName(_fromUtf8("advancedIntersectionLayer"))
        self.gridLayout_11.addWidget(self.advancedIntersectionLayer, 2, 1, 1, 2)
        self.reportField = gui.QgsFieldComboBox(self.groupBox_4)
        self.reportField.setObjectName(_fromUtf8("reportField"))
        self.gridLayout_11.addWidget(self.reportField, 4, 1, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.intersectionTab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.simpleIntersectionWritePoint = QtGui.QCheckBox(self.groupBox_5)
        self.simpleIntersectionWritePoint.setObjectName(_fromUtf8("simpleIntersectionWritePoint"))
        self.gridLayout_12.addWidget(self.simpleIntersectionWritePoint, 0, 0, 1, 1)
        self.simpleIntersectionLayer = gui.QgsMapLayerComboBox(self.groupBox_5)
        self.simpleIntersectionLayer.setObjectName(_fromUtf8("simpleIntersectionLayer"))
        self.gridLayout_12.addWidget(self.simpleIntersectionLayer, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.intersectionTab, _fromUtf8(""))
        self.dimensionTab = QtGui.QWidget()
        self.dimensionTab.setObjectName(_fromUtf8("dimensionTab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.dimensionTab)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 0, 3, 1, 1)
        self.dimensionOrientationWrite = QtGui.QGroupBox(self.dimensionTab)
        self.dimensionOrientationWrite.setCheckable(True)
        self.dimensionOrientationWrite.setObjectName(_fromUtf8("dimensionOrientationWrite"))
        self.gridLayout_6 = QtGui.QGridLayout(self.dimensionOrientationWrite)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_11 = QtGui.QLabel(self.dimensionOrientationWrite)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.dimensionOrientationObservationWrite = QtGui.QCheckBox(self.dimensionOrientationWrite)
        self.dimensionOrientationObservationWrite.setChecked(True)
        self.dimensionOrientationObservationWrite.setObjectName(_fromUtf8("dimensionOrientationObservationWrite"))
        self.gridLayout_6.addWidget(self.dimensionOrientationObservationWrite, 1, 0, 1, 1)
        self.dimensionOrientationPrecisionWrite = QtGui.QCheckBox(self.dimensionOrientationWrite)
        self.dimensionOrientationPrecisionWrite.setObjectName(_fromUtf8("dimensionOrientationPrecisionWrite"))
        self.gridLayout_6.addWidget(self.dimensionOrientationPrecisionWrite, 2, 0, 1, 1)
        self.dimensionOrientationLayer = gui.QgsMapLayerComboBox(self.dimensionOrientationWrite)
        self.dimensionOrientationLayer.setObjectName(_fromUtf8("dimensionOrientationLayer"))
        self.gridLayout_6.addWidget(self.dimensionOrientationLayer, 0, 1, 1, 1)
        self.dimensionOrientationObservationField = gui.QgsFieldComboBox(self.dimensionOrientationWrite)
        self.dimensionOrientationObservationField.setObjectName(_fromUtf8("dimensionOrientationObservationField"))
        self.gridLayout_6.addWidget(self.dimensionOrientationObservationField, 1, 1, 1, 1)
        self.dimensionOrientationPrecisionField = gui.QgsFieldComboBox(self.dimensionOrientationWrite)
        self.dimensionOrientationPrecisionField.setEnabled(False)
        self.dimensionOrientationPrecisionField.setObjectName(_fromUtf8("dimensionOrientationPrecisionField"))
        self.gridLayout_6.addWidget(self.dimensionOrientationPrecisionField, 2, 1, 1, 1)
        self.gridLayout_9.addWidget(self.dimensionOrientationWrite, 3, 1, 1, 2)
        self.dimensionDistanceWrite = QtGui.QGroupBox(self.dimensionTab)
        self.dimensionDistanceWrite.setCheckable(True)
        self.dimensionDistanceWrite.setObjectName(_fromUtf8("dimensionDistanceWrite"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dimensionDistanceWrite)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_10 = QtGui.QLabel(self.dimensionDistanceWrite)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.dimensionDistanceObservationWrite = QtGui.QCheckBox(self.dimensionDistanceWrite)
        self.dimensionDistanceObservationWrite.setChecked(True)
        self.dimensionDistanceObservationWrite.setObjectName(_fromUtf8("dimensionDistanceObservationWrite"))
        self.gridLayout_5.addWidget(self.dimensionDistanceObservationWrite, 1, 0, 1, 1)
        self.dimensionDistancePrecisionWrite = QtGui.QCheckBox(self.dimensionDistanceWrite)
        self.dimensionDistancePrecisionWrite.setObjectName(_fromUtf8("dimensionDistancePrecisionWrite"))
        self.gridLayout_5.addWidget(self.dimensionDistancePrecisionWrite, 2, 0, 1, 1)
        self.dimensionDistanceLayer = gui.QgsMapLayerComboBox(self.dimensionDistanceWrite)
        self.dimensionDistanceLayer.setObjectName(_fromUtf8("dimensionDistanceLayer"))
        self.gridLayout_5.addWidget(self.dimensionDistanceLayer, 0, 1, 1, 1)
        self.dimensionDistancePrecisionField = gui.QgsFieldComboBox(self.dimensionDistanceWrite)
        self.dimensionDistancePrecisionField.setEnabled(False)
        self.dimensionDistancePrecisionField.setObjectName(_fromUtf8("dimensionDistancePrecisionField"))
        self.gridLayout_5.addWidget(self.dimensionDistancePrecisionField, 2, 1, 1, 1)
        self.dimensionDistanceObservationField = gui.QgsFieldComboBox(self.dimensionDistanceWrite)
        self.dimensionDistanceObservationField.setObjectName(_fromUtf8("dimensionDistanceObservationField"))
        self.gridLayout_5.addWidget(self.dimensionDistanceObservationField, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.dimensionDistanceWrite, 0, 1, 1, 2)
        self.tabWidget.addTab(self.dimensionTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Settings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(_translate("Settings", "Intersect It :: settings", None))
        self.selectGroup.setTitle(_translate("Settings", "Map", None))
        self.label.setText(_translate("Settings", "select objects within", None))
        self.pixels.setText(_translate("Settings", "pixels", None))
        self.map.setText(_translate("Settings", "map units", None))
        self.rubberIcon.setItemText(0, _translate("Settings", "None", None))
        self.rubberIcon.setItemText(1, _translate("Settings", "+", None))
        self.rubberIcon.setItemText(2, _translate("Settings", "X", None))
        self.rubberIcon.setItemText(3, _translate("Settings", "□", None))
        self.rubberIcon.setItemText(4, _translate("Settings", "O", None))
        self.label_2.setText(_translate("Settings", "rubber band size and color", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), _translate("Settings", "General", None))
        self.groupBox.setTitle(_translate("Settings", "Distances", None))
        self.label_3.setText(_translate("Settings", "Default precision for distances [m]", None))
        self.groupBox_3.setTitle(_translate("Settings", "Orientations", None))
        self.label_4.setText(_translate("Settings", "Default precision for orientations [°]", None))
        self.label_8.setText(_translate("Settings", "Length of drawn line", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.observationTab), _translate("Settings", "Observations", None))
        self.groupBox_4.setTitle(_translate("Settings", "Advanced intersection", None))
        self.advancedIntersectionWriteReport.setText(_translate("Settings", "write intersection report in field", None))
        self.advancedIntersectionWritePoint.setText(_translate("Settings", "write point in layer", None))
        self.label_6.setText(_translate("Settings", "m", None))
        self.label_5.setText(_translate("Settings", "Least-squares Convergence threshold", None))
        self.label_7.setText(_translate("Settings", "Maximum iterations", None))
        self.groupBox_5.setTitle(_translate("Settings", "Simple intersection", None))
        self.simpleIntersectionWritePoint.setText(_translate("Settings", "write point in layer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.intersectionTab), _translate("Settings", "Intersection", None))
        self.dimensionOrientationWrite.setTitle(_translate("Settings", "place orientation dimensions", None))
        self.label_11.setText(_translate("Settings", "in layer", None))
        self.dimensionOrientationObservationWrite.setText(_translate("Settings", "place observation value in", None))
        self.dimensionOrientationPrecisionWrite.setText(_translate("Settings", "place precision in", None))
        self.dimensionDistanceWrite.setTitle(_translate("Settings", "place distance dimensions", None))
        self.label_10.setText(_translate("Settings", "in layer", None))
        self.dimensionDistanceObservationWrite.setText(_translate("Settings", "place observation value in", None))
        self.dimensionDistancePrecisionWrite.setText(_translate("Settings", "place precision in", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dimensionTab), _translate("Settings", "Dimensions", None))

from qgis import gui
